server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securecapira?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password:
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL81nnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate :
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init :
      mode: never
